services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=bank_db
        ports:
            - "5432:5432"
        volumes:
            - data-volume:/var/lib/postgresql/data
    # redis:
    #     image: redis:7-alpine
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
            - "9090:9090"
        environment:
            - DB_SOURCE=postgresql://root:root@postgres:5432/bank_db?sslmode=disable
            # - REDIS_ADDRESS=redis:6379
        depends_on:
            - postgres
            # - redis
        entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
        command: ["/app/main"]
volumes:
    data-volume:
