# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
    push:
        branches: ["dev"]
    pull_request:
        branches: ["dev"]

jobs:
    build:
        runs-on: ubuntu-latest
        # Service containers to run with `container-job`
        services:
            # Label used to access the service container
            postgres:
                # Docker Hub image
                image: postgres:latest
                # Provide the password for postgres
                env:
                    POSTGRES_DB: bank_db
                    POSTGRES_USER: root
                    POSTGRES_PASSWORD: root
                ports:
                    - 5432:5432
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22.1"

            - name: Init golang-migrate
              run: |
                  curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
                  sudo mv migrate.linux-amd64 /usr/bin/migrate
                  which migrate # just for check

            - name: Run migrations
              run: make migrateup

            - name: Test
              run: make test
